name: dl
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6.9
  - numba=0.48.0
  - scikit-image=0.15.0
  - scipy=1.3.1
  - tqdm=4.42.1
  - numpy==1.18.1
  - opencv=3.4.2
  - pytorch
  - torchvision
  - pytest
  - neovim
